### PR TITLE
Anuj98/remove unecessary scrolls

### LINKED ISSUE #100: Remove ugly scrollbars from the page
image

### PR DESCRIPTION
**Pull request by anuj98**
Removed the extra scrolls from the page 

image

Closes #100.

### CODE REVIEW

**Comment by zsol** [comment]
lgtm but I'm no pixel pusher 😆 let's see if @anathien has anything to say

**Comment by zsol** [comment]
@anuj98 just FYI I updated the PR text to say `Closes #100` at the end. This way Github will automatically close the issue when the PR is merged

**Comment by anuj98** [comment]
@anathien Please review this PR

**Review by anathien — APPROVED** [review]
Looks about right 🙂 Thanks for fixing! 
Weirdly, this bug didn't show up on my M1/Chrome setup O.o

**Comment by zsol** [comment]
Thanks @anuj98! @all-contributors let's add @anuj98 for their code contribution.

**Pull request merged**
